import type { Metadata } from 'next';
import '@/app/globals.css';
import { plexSans } from '@/fonts/font';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <head>
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
          />
        </head>
        <body
          className={`${plexSans.className} antialiased text-[#121318] dark:text-[#eaecef] dark:bg-[#181a20]`}
        >
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
