name: Auto Version Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          latestTag=$(git describe --tags --abbrev=0 || echo "v0.1.0")
          echo "latest=$latestTag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          latest=${{ steps.get_tag.outputs.latest }}
          version=${latest#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new="v$major.$minor.$patch"
          echo "new_tag=$new" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
