name: Otomatik Versiyon Artırma ve Tag Oluşturma

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Versiyonu Artır ve Tag Oluştur
        uses: anothrNick/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
